# -*- coding: utf-8 -*-
"""question-0003-usecase-generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/188xhv-4mfLUvDL4UQCznQ-tgLoqodOVy
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import KBinsDiscretizer

def generar_caso_de_uso_discretizar_ingresos():
    n_rows = 15
    df_input = pd.DataFrame({'ingresos': np.random.uniform(1000, 10000, n_rows)})
    bins = 3
    input_data = {'df': df_input.copy(), 'n_bins': bins}

    est = KBinsDiscretizer(n_bins=bins, encode='ordinal', strategy='uniform')
    output_expected = est.fit_transform(df_input[['ingresos']])

    return input_data, output_expected