# -*- coding: utf-8 -*-
"""question-0001-usecase-generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P6nOlJ8Gqlk_SAoE2wcD2zswnbIZgEaP
"""

import pandas as pd
import numpy as np
import random

def generar_caso_de_uso_detectar_olas_calor():
    n_rows = random.randint(10, 15)
    fechas = pd.date_range(start='2023-01-01', periods=n_rows).strftime('%Y-%m-%d').tolist()
    df_input = pd.DataFrame({
        'fecha': fechas,
        'temperatura': [random.uniform(20, 45) for _ in range(n_rows)]
    })
    umbral = 35.0
    input_data = {'df': df_input.copy(), 'umbral': umbral}

    df_expected = df_input.copy()
    df_expected['fecha'] = pd.to_datetime(df_expected['fecha'])
    df_expected['dia_semana'] = df_expected['fecha'].dt.day_name()
    df_expected = df_expected[df_expected['temperatura'] > umbral]

    return input_data, df_expected