# -*- coding: utf-8 -*-
"""question-0002-usecase-generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NTufS1aW2kZZ7eq_TcFIwawdfB73FsJX
"""

import pandas as pd
import numpy as np

def generar_caso_de_uso_limpiar_outliers_iqr():
    data = {'presion_arterial': [120, 122, 118, 125, 190, 121, 119, 40, 123, 122]}
    df_input = pd.DataFrame(data)
    col = 'presion_arterial'
    input_data = {'df': df_input.copy(), 'columna': col}

    q1 = df_input[col].quantile(0.25)
    q3 = df_input[col].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    df_expected = df_input[(df_input[col] >= lower) & (df_input[col] <= upper)]

    return input_data, df_expected