# -*- coding: utf-8 -*-
"""question-0004-usecase-generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14xGKJKlLRKR7HJxsbA8N8Mft-bzawNzT
"""

import numpy as np
from sklearn.feature_selection import VarianceThreshold

def generar_caso_de_uso_eliminar_baja_varianza():
    # Columna 0: varianza alta, Columna 1: varianza cero, Columna 2: varianza media
    X = np.array([
        [10, 1, 0.5],
        [20, 1, 0.6],
        [30, 1, 0.4],
        [40, 1, 0.8]
    ])
    u = 0.1
    input_data = {'X_matrix': X, 'umbral': u}

    selector = VarianceThreshold(threshold=u)
    output_expected = selector.fit_transform(X)

    return input_data, output_expected