# -*- coding: utf-8 -*-
"""answer-0011

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19PP_6tuaWAlxb9Y4-1TgX8jlweoGatwM
"""

import numpy as np
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

def pipeline_pca_regresion(X_train, y_train, X_test, n_components):

    pipeline = Pipeline([
        ("pca", PCA(n_components=n_components)),
        ("regresion", LinearRegression())
    ])

    pipeline.fit(X_train, y_train)

    return pipeline.predict(X_test)