# -*- coding: utf-8 -*-
"""answer-0373

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X63I0YcceQH8XKqaYLF9-GqzmnYcLGYu
"""

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

def evaluar_calidad_clustering(df, columnas, n_clusters):
    X = df[columnas].to_numpy()

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    kmeans = KMeans(
        n_clusters=n_clusters,
        n_init=10,
        random_state=42
    )

    labels = kmeans.fit_predict(X_scaled)

    score = silhouette_score(X_scaled, labels)

    return score
