# -*- coding: utf-8 -*-
"""answer-0587

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ToEUR_z2HuowMULD_Y3EzwReHsyLDyYo
"""

import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.metrics import (
    make_scorer,
    accuracy_score,
    precision_score,
    recall_score
)

def evaluar_clasificador(X, y, modelo):
    pipeline = Pipeline([
        ('scaler', StandardScaler()),
        ('clasificador', modelo)
    ])

    cv = StratifiedKFold(
        n_splits=5,
        shuffle=True,
        random_state=42
    )

    scoring = {
        'accuracy': make_scorer(accuracy_score),
        'precision': make_scorer(
            precision_score,
            average='weighted',
            zero_division=0
        ),
        'recall': make_scorer(
            recall_score,
            average='weighted',
            zero_division=0
        )
    }

    resultados = cross_validate(
        pipeline,
        X,
        y,
        cv=cv,
        scoring=scoring
    )

    return {
        metrica: {
            'media': round(float(np.mean(resultados[f'test_{metrica}'])), 4),
            'std': round(float(np.std(resultados[f'test_{metrica}'])), 4)
        }
        for metrica in ['accuracy', 'precision', 'recall']
    }
