# -*- coding: utf-8 -*-
"""answer-0064

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V4xB6LZm1Av_tYU_o2pMpHjsFyJVU8Z5
"""

import pandas as pd
import numpy as np
from sklearn.decomposition import PCA

def verificar_integridad_senal(X_train, X_test, threshold_percentile=95):

    pca = PCA(
        n_components=0.9,
        svd_solver='full'
    )

    pca.fit(X_train)

    X_test_reduced = pca.transform(X_test)
    X_test_reconstructed = pca.inverse_transform(X_test_reduced)

    diferencia = X_test.values - X_test_reconstructed

    mse_fila = np.mean(
        np.square(diferencia),
        axis=1
    )

    umbral = np.percentile(
        mse_fila,
        threshold_percentile
    )

    resultado_df = X_test.copy()

    resultado_df['alerta_integridad'] = (
        mse_fila > umbral
    )

    return resultado_df
